const colleges = {
  "List of Colleges": {
    "College of Arts and Science": [
      "BACHELOR OF ARTS IN COMMUNICATION (BA-COMM)",
      "BACHELOR OF ARTS IN INTERNATIONAL STUDIES (BA-IS)",
      "BACHELOR OF ARTS IN POLITICAL SCIENCE (BA-PS)",
      "BACHELOR OF SCIENCE IN BIOLOGY (BS-BIO)",
      "BACHELOR OF SCIENCE IN PSYCHOLOGY (BS-PSYCH)",
      "BACHELOR OF ARTS AND MAJOR IN FILM AND MEDIA STUDIES",
      "BACHELOR OF SCIENCE IN MATHEMATICS",
      "BACHELOR OF ARTS IN INTERNATIONAL STUDIES",
      "BACHELOR OF ARTS IN ENGLISH LITERATURE",
      "BACHELOR OF ARTS IN ECONOMICS",
      "BACHELOR OF ARTS IN POLITICAL SCIENCE",
      "MASTER OF MANAGEMENT IN PUBLIC MANAGEMENT",
      "MASTER OF MUSIC IN PEDAGOGY(MUSIC EDUCATION)",
      "MASTER OF MUSIC IN PERFORMANCE",
      "MASTER IN LOCAL GOVERNANCE",
      "DIPLOMA IN LOCAL GOVERNANCE",
    ],
    "School of Business, Management and Accountancy": [
      "MASTER OF BUSINESS ADMINISTRATION",
      "MASTER IN MANAGEMENT MAJOR IN HUMAN RESOURCE MANAGEMENT",
      "MASTER IN MANAGEMENT MAJOR IN BUSINESS MANAGEMENT",
      "MASTE IN MANAGEMENT MAJOR IN INSTRUCTIONAL SYSTEM MANAGEMENT",
      "DOCTOR IN MANAGEMENT MAJOR IN LEADERSHIP & ORGANIZATION",
      "DOCTOR IN MANAGEMENT MAJOR IN HUMAN RESOURCE MANAGEMENT",
      "BACHELOR OF SCIENCE IN ACCOUNTANCY",
      "BACHELOR OF SCIENCE IN MANAGEMENT ACCOUNTING",
      "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION",
      "BACHELOR OF SCIENCE IN REAL ESTATE MANAGEMENT",
      "BACHELOR OF SCIENEC IN HOSPITALITY MANAGEMENT",
      "BACHELOR OF SCIENCE IN TOURISM MANAGEMENT"
    ],
    "College of Criminal Justice": [
      "BACHELOR OF SCIENCE IN CRIMINOLOGY"
    ],
    "College of Engineering": [
      "MASTER IN MANAGEMENT MAJOR IN MANAGEMENT ENGINEERING",
      "MASTER IN MANAGEMENT MAJOR IN ENVIRONMENT PLANNING MANAGEMENT",
      "BACHELOR OF SCIENCE IN CIVIL ENGINEERING (BSCE)",
      "BACHELOR OF SCIENCE IN COMPUTER ENGINEERING (BSCPE)",
      "BACHELOR OF SCIENCE IN ELECTRICAL ENGINEERING (BSEE)",
      "BACHELOR OF SCIENCE IN ELECTRONICS ENGINEERING (BSECE)",
      "BACHELOR OF SCIENCE IN INDUSTRIAL ENGINEERING (BSIE)"
    ],
    "College of Information Technology": [
      "ASSOCIATE IN COMPUTER TECHNOLOGY",
      "BACHELOR OF LIBRARY AND INFORMATION SCIENCE",
      "BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY (BSIT)",
      "ASSOCIATE IN COMPUTER TECHNOLOGY (ACT)",
      "MASTER OF SCIENCE IN INFORMATION TECHNOLOGY",
      "MASTER IN LIBRARY AND INFORMATION SCIENCE",
      "MASTER IN MANAGEMENT MAJOR IN INFORMATION TECHNOLOGY MANAGEMENT",
    ],
    "College of Medical Laboratory Science": [
      "BACHELOR OF SCIENCE IN MEDICAL TECHNOLOGY/BACHELOR OF SCIENCE IN MEDICAL LABORATORY SCIENCE (BSMT/BSMLS)"
    ],
    "Conservatory of Music, Theater and Dance": [
      "BACHELOR OF MUSIC",
      "BACHELOR OF MUSIC IN PERFORMANCE",
      "BACHELOR OF MUSIC IN CHURCH MUSIC",
      "BACHELOR OF MUSIC IN MUSIC MANAGEMENT",
      "BACHELOR OF MUSIC IN ORCHESTRAL CONDUCTING",
      "BACHELOR OF MUSIC IN PERCUSSION PERFORMANCE",
      "BACHELOR OF MUSIC IN PEDAGOGY",
      "BACHELOR OF MUSIC IN THEATER",
      "ASSOCIATE IN MUSIC",
      "ARTIST DIPLOMA"
    ],
    "College of Nursing": [
      "BACHELOR OF SCIENCE IN NURSING",
      "MASTER OF ARTS IN NURSING",
      "MASTER IN NURSING",
      "DOCTOR IN MANAGEMENT MAJOR IN HEALTH CARE ADMINISTRATION"
    ],
    "College of Pharmacy": [
      "BACHELOR OF SCIENCE IN PHARMACY (BSP)",
      "BACHELOR OF SCIENCE IN NURSING",
      "BACHELOR OF SCIENCE IN MEDICAL LABORATORY SCIENCE",
      "BACHELOR OF SCIENCE IN OCCUPATIONAL THERAPY",
      "BACHELOR OF SCIENCE IN PHYSICAL THERAPY",
      "BACHELOR OF SCIENCE IN RADIOLOGIC TECHNOLOGY",
      "DOCTOR OF MANAGEMENT MAJOR IN HEALTH CARE ADMINISTRATION",
      "MASTER OF ARTS IN NURSING",
      "MASTER IN NURSING"
    ],
    "College of Rehabilitation Science": [
      "BACHELOR OF SCIENCE IN OCCUPATIONAL THERAPY (BSOT)",
      "BACHELOR OF SCIENCE IN PHYSICAL THERAPY (BSPT)"
    ],
    "College of Radiologic Technology": [
      "BACHELOR OF SCIENCE IN RADIOLOGIC TECHNOLOGY"
    ],
    "School of Teacher Education": [
      "BACHELOR OF EARLY CHILDHOOD EDUCATION",
      "BACHELOR OF ELEMENTARY EDUCATION (BEED)",
      "BACHELOR OF PHYSICAL EDUCATION (BPED)",
      "BACHELOR OF SECONDARY EDUCATION MAJOR IN SOCIAL STUDIES, ENGLISH, MATH, SCIENCES, FILIPINOS.",
      "BACHELOR OF SPECIAL NEEDS EDUCATION (GENERALIST)",
      "DOCTOR OF EDUCATION MAJOR IN EARLY CHILDHOOD EDUCATION LEADERSHIP & MANAGEMENT",
      "MASTER OF ARTS IN EDUCATION"
    ]
  }
};

export default colleges;